import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className=''>
      <Head>
        <title>Lemon Hive</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
          <div>
            <h1 className=' text-darkblue font-bold text-h1 text-right max-w-[804px] leading-[125px]'>React Conference</h1>
          </div>
      </main>
      
    </div>
  )
}
