import Head from "next/head";
import Hero from "../components/Hero";
import Schedule from "../components/Schedule";


export default function Home() {
	return (
		<div className=' relative w-full'>
			<Head>
				<title>Lemon Hive</title>
				<meta
					name='description'
					content='Generated by create next app'
				/>
				<link rel='icon' href='/favicon.ico' />
			</Head>
			
      
      <Hero />
      <div className='h-[150px]'></div>
      <Schedule />

			{/* gradients */}
			<div className=' custom-gradient-2  absolute lg:top-[-50px] lg:left-0 z-10 lg:w-[490px] lg:h-[428px]'></div>
			<div className=' custom-gradient absolute sm:top-0 sm:right-0 lg:top-[-25px] lg:right-0 sm:w-[141px] sm:h-[141px] lg:w-[412px] lg:h-[412px]'></div>
			<div className='custom-gradient-3 absolute sm:w-[194px] sm:h-[192px] lg:w-[383px] lg:h-[383px] top-0 left-0 '></div>
		</div>
	);
}
